apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-image-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-image-demo
  template:
    metadata:
      labels:
        app: nodejs-image-demo
    spec:
      containers:
      - name: nodejs-image-demo-container
        image: docker6767account/devimage
        ports:
        - containerPort: 8080
