apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-deployment
  labels:
    app: shark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shark
  template:
    metadata:
      labels:
        app: shark
    spec:
      containers:
      - name: shark
        image: docker6767/secureimage
        ports:
        - containerPort: 80
