apiVersion: v1
kind: Service
metadata:
  name: nodejs-image-demo-service
spec:
  type: NodePort
  selector:
    app: nodejs-image-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

